### ISSUE TITLE
If reclaiming tokens after transfer ownership, tokens go to original owner

### ISSUE THREAD

**Issue by OperationNine** [BlockchainLabsNZ/bluzelle-contracts#6]
After transferring ownership to a new address, and then subsequently calling `reclaimTokens()` this results in tokens being send to the old owner instead of the new one.

**Comment by OperationNine** [comment]
Works as intended, tokens were successfully transferred to original owner:

https://kovan.etherscan.io/address/0x00b0279b9b96a44a0e0f83ecba17d65433fa9159#tokentxns

**Comment by OperationNine** [comment]
Initiated ownership from original owner: `0x00b0279b9b96a44a0e0f83ecba17d65433fa9159`

https://kovan.etherscan.io/tx/0x30ed1184e60fba682f6b9e4dd79ad18a7662f4a2bf3a6dc224b46166a24c7913

Complete transferred ownership: `0xa01b6ae65e2e3821696ae7de99352d61a6960199`

https://kovan.etherscan.io/tx/0x414244f86b8d9801a1d7b209f7b88dab53f652f65d7cc89103998272de9ba55e

Reclaim tokens called by new owner: `0xa01b6ae65e2e3821696ae7de99352d61a6960199`

https://kovan.etherscan.io/tx/0xa502819d7a74daf8ad268a64fdb526a47ecf6327b06915f5b7c0b3949d1e361f

Remaining tokens are transferred to the old owner instead of the new owner: `0x00b0279b9b96a44a0e0f83ecba17d65433fa9159`

https://kovan.etherscan.io/tx/0xa502819d7a74daf8ad268a64fdb526a47ecf6327b06915f5b7c0b3949d1e361f

https://kovan.etherscan.io/token/0x21dd890aa108fc1cd987450dd50fb57f0476a3a3?a=0x00b0279b9b96a44a0e0f83ecba17d65433fa9159

**Comment by matt-lough** [comment]
The [`reclaimTokens`](https://github.com/njmurarka/ico-solidity/blob/master/contracts/Enuma/FlexibleTokenSale.sol#L334) function for the TokenSale  contract transfers tokens back to the owner of the Token contract.

The [`reclaimTokens`](https://github.com/njmurarka/ico-solidity/blob/master/contracts/BluzelleToken.sol#L41) function for the Token contract transfers tokens to the owner of the Token contract. 

The `initiateOwnershipTransfer` in the above tests was from the TokenSale contract so this behaviour is expected. You must change the owner of the Token contract if you want the tokens to be transferred to a different owner.
